version: '3'
services:
  db:
    image: postgres:14.8
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$MEMORY_UPDATE_APP_DATABASE_PASSWORD
      - POSTGRES_USER=memory_update_app
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    depends_on:
      - db
    command: redis-server
  sidekiq:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
    command: bundle exec sidekiq
volumes:
  postgres:
  redis: